---
- name: Install code extension
  ansible.builtin.shell: |
    code --install-extension {{ vscode_extension }}
  loop: "{{ vscode_extensions }}"
  loop_control:
    loop_var: vscode_extension

- name: Create settings vscode
  ansible.builtin.template:
    src: vscode_settings.json.j2
    dest: /home/{{ ansible_facts['user_id'] }}/.config/Code/User/settings.json
    mode: 0644
  when: vscode_config | length >= 1

- name: Create keybindings vscode
  ansible.builtin.template:
    src: vscode_keybindings.json.j2
    dest: /home/{{ ansible_facts['user_id'] }}/.config/Code/User/keybindings.json
    mode: 0644
  when: vscode_keybindings | length >= 1
